server.port=6060
spring.application.name=aeo-content-analyzer


spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}

# Gemini API
gemini.api.key=${GEMINI_API_KEY}
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent
openrouter.api.key=${OPENROUTER_API_KEY}

# RAG Service
rag.service.url=http://localhost:8090

# Security
spring.security.user.name=${APP_USERNAME:admin}
spring.security.user.password=${APP_PASSWORD:admin123}

# Logging
logging.level.root=INFO
logging.level.org.springframework.web=INFO
logging.level.com.aeo.analyzer=DEBUG

# Actuator
management.endpoints.web.exposure.include=health,info
