#spring.application.name=analyzer

#spring.profiles.active=dev

# ===============================
# DEVELOPMENT CONFIGURATION (Local)
# ===============================

# Server Port
server.port=6060

# Application Name
spring.application.name=aeo-content-analyzer

# 1. MongoDB Configuration (Local)
spring.data.mongodb.uri=${MONGODB_URI}

# 2. Gemini API Configuration
gemini.api.key=${GEMINI_API_KEY}
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent
openrouter.api.key=${OPENROUTER_API_KEY}

# 3. Python RAG Service (Local)
rag.service.url=http://localhost:8090

# Security Configuration (Test)
spring.security.user.name=${APP_USERNAME}
spring.security.user.password=${APP_PASSWORD}

# Logging Levels
logging.level.root=INFO
logging.level.org.springframework.web=INFO
logging.level.com.aeo.analyzer=DEBUG

-Djdk.tls.client.protocols=TLSv1.2

# DevTools & Actuator
spring.devtools.add-properties=false
management.endpoints.web.exposure.include=health,info